name: CI/CD Pipeline for Weather App

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate with Google Cloud 
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simple-python-app/python-app:latest .

      # Push Docker image to Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          echo "Pushing Docker image to Artifact Registry..."
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simple-python-app/python-app:latest

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          echo "Installing gke-gcloud-auth-plugin..."
          gcloud components install gke-gcloud-auth-plugin --quiet

      # Get GKE credentials
      - name: Get GKE credentials
        run: |
          echo "Fetching GKE credentials..."
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}

      # Deploy to GKE
      - name: Deploy to GKE
        run: |
          echo "Updating deployment in GKE..."
          kubectl set image deployment/python-app-cluster python-app=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/simple-python-app/python-app:latest
